name: Build
on: [push, workflow_dispatch]

jobs:
  create-and-annotate-sbml:
    uses: jwkruisselbrink/sbml-pbk-workflow/.github/workflows/build.yml@v8
    with:
      model-name: euromix
    permissions:
      contents: write
    secrets: inherit
