# .github/workflows/test_action.yaml
name: Create and annotate SBML
on: [push, workflow_dispatch]

jobs:
  create-and-annotate-sbml:
    uses: jwkruisselbrink/sbml-pbk-workflow/.github/workflows/build.yml@main
    with:
      model-name: euromix
    permissions:
      contents: write
    secrets: inherit
